version: '3.8'

services:
  db:
    container_name: nest_db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: nest_db
      PGDATA: /data/postgres
    volumes:
      - .data/postgres:/data/postgres
